FROM odanado/book:base

USER root

RUN apt update && \
    apt install -y npm --no-install-recommends && \
    apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

USER $NB_USER

RUN npm config set prefix $HOME/.local && \
    npm install -g textlint textlint-rule-preset-ja-technical-writing \
    textlint-filter-rule-comments textlint-rule-spellcheck-tech-word && \
    npm cache clean
